language: python

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      python: 3.5
      compiler: clang
    - os: linux
      python: 3.5
      compiler: gcc
    - os: linux
      python: 3.6
      compiler: clang
    - os: linux
      python: 3.6
      compiler: gcc
    - os: osx
      python: 3.5
      compiler: clang
    - os: osx
      python: 3.5
      compiler: gcc
    - os: osx
      python: 3.6
      compiler: clang
    - os: osx
      python: 3.6
      compiler: gcc

before_install:
  - pip install codecov
  - pip install pytest --upgrade
  - pip install pytest-cov
    
install:
  - python setup.py install
    
  